### ISSUE TITLE
Hash#fetch with second argument is slower than Hash#fetch with block is not FAIR

### ISSUE THREAD

**Issue by greyblake** [JuanitoFatas/fast-ruby#117]
Hi! First of all thanks for the nice gem! You are doing great work, making thousand of ruby programs run faster!

Now.. the issue)

Offense `Hash#fetch with second argument is slower than Hash#fetch with block`is not fair.

You have this benchamrk: https://github.com/JuanitoFatas/fast-ruby/blob/master/code/hash/fetch-vs-fetch-with-block.rb

``` ruby
require "benchmark/ips"

HASH = { writing: :fast_ruby }
DEFAULT = "fast ruby"

Benchmark.ips do |x|
  x.report("Hash#fetch + const") { HASH.fetch(:writing, DEFAULT) }
  x.report("Hash#fetch + block") { HASH.fetch(:writing) { "fast ruby" } }
  x.report("Hash#fetch + arg")   { HASH.fetch(:writing, "fast ruby") }
  x.compare!
end
```

But it's assuming that key is always present. What is not really? Otherwise why one passes default value?

Here is my benchmark with `hit` and `miss` cases:

``` ruby
require 'benchmark'

N = 10_000_000

hash = { a: 10, b: 20, c: 30, e: 40 }

Benchmark.bm(15, "rescue/condition") do |x|
  x.report("with 2nd arg (hit) ") do
    N.times { hash.fetch(:a, false) }
  end

  x.report("with block (hit)   ") do
    N.times { hash.fetch(:a) { false } }
  end

  x.report("with 2nd arg (miss)") do
    N.times { hash.fetch(:x, false) }
  end

  x.report("with block (miss)  ") do
    N.times { hash.fetch(:x) { false } }
  end
end
```

Here is the output (ruby 2.1.5p273):

```
                      user     system      total        real
with 2nd arg (hit)   1.050000   0.000000   1.050000 (  1.041781)
with block (hit)     1.030000   0.000000   1.030000 (  1.031664)
with 2nd arg (miss)  1.010000   0.000000   1.010000 (  1.010886)
with block (miss)    1.760000   0.000000   1.760000 (  1.755389)
```

You see that `with 2nd arg (hit)` and `with 2nd arg (hit)` is almost the same, but diff between `with 2nd arg (miss)` and `with block (miss)` is quite big.

So, IMHO, this offense is not fair and it should be removed.

Thanks!

**Comment by seanabrahams** [comment]
Have to agree. Here's some output from ruby 2.3.4p301 which has the block format slower on my machine:
```
                      user     system      total        real
with 2nd arg (hit)   0.580000   0.000000   0.580000 (  0.578319)
with block (hit)     0.610000   0.000000   0.610000 (  0.616988)
with 2nd arg (miss)  0.630000   0.000000   0.630000 (  0.631783)
with block (miss)    0.990000   0.000000   0.990000 (  0.989013)
```

**Comment by eclemens** [comment]
The same for me using ruby-2.4.4p296

```
                      user     system      total        real
with 2nd arg (hit)   0.570000   0.000000   0.570000 (  0.571392)
with block (hit)     0.570000   0.000000   0.570000 (  0.569225)
with 2nd arg (miss)  0.570000   0.000000   0.570000 (  0.568199)
with block (miss)    1.030000   0.000000   1.030000 (  1.037917)
```

**Comment by ixti** [comment]
`Hash#fetch` with second arg being a constant is known to be the fastest way. It was [already discussed](https://github.com/JuanitoFatas/fast-ruby/issues/39#issuecomment-103989335) and actually has a pretty clear [disclaimer/explanation](https://github.com/JuanitoFatas/fast-ruby#hashfetch-with-argument-vs-hashfetch--block-code):

> Note that the speedup in the block version comes from avoiding repeated
> construction of the argument. If the argument is a constant, number symbol or
> something of that sort the argument version is actually slightly faster
