### ISSUE TITLE
Needs an article on JRUBY vs MRI

### ISSUE THREAD

**Issue by ninkibah** [JuanitoFatas/fast-ruby#23]
I'm running the benchmarks under JRUBY. I will analyse the results and compare them with MRI, because the community needs to know if some of the recommendations for MRI are bad for JRuby code and vice versa.

Can I add a Wiki page? Would that be the best?

**Comment by JuanitoFatas** [comment]
Hi Jonathan!

Thanks so much for taking your time writing this issue. I am not familiar with JRuby but would love to learn from you. Please do write a Wiki page then we can link from README as a start. 

Thanks again! :smile: 

/cc @headius

**Comment by JuanitoFatas** [comment]
Done by [JRuby Performance results](https://github.com/JuanitoFatas/fast-ruby/wiki/JRuby-Performance-results).

**Comment by headius** [comment]
:+1:
