### ISSUE TITLE
Block vs. Symbol#to_proc

### ISSUE THREAD

**Issue by nning** [JuanitoFatas/fast-ruby#24]
[Your example shows that the Block variant is slower.](https://github.com/JuanitoFatas/fast-ruby#block-vs-symbolto_proc-code) I remembered measuring the allegedly same with different results, so I looked again at the code files. Turns out I used an Array instead of a Range.

If I change the Range to an Array in [line 3 of `code/proc-and-block/block-vs-to_proc.rb`](https://github.com/JuanitoFatas/fast-ruby/blob/master/code/proc-and-block/block-vs-to_proc.rb#L3), the benchmark yields inverted results:

    $ ruby -v code/proc-and-block/block-vs-to_proc.rb
    ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
    
    Calculating -------------------------------------
                   Block    51.849k i/100ms
          Symbol#to_proc    48.724k i/100ms
    -------------------------------------------------
                   Block      1.075M (± 0.7%) i/s -      5.392M
          Symbol#to_proc    937.576k (± 0.8%) i/s -      4.726M
    
    Comparison:
                   Block:  1075189.7 i/s
          Symbol#to_proc:   937575.7 i/s - 1.15x slower

So Block vs. Symbol#to_proc efficiency seems to depend on the object operated on.

**Comment by JuanitoFatas** [comment]
Hallo @nning,

Could you show me the code you run with above result? On my machine Symbol#to_proc is faster with range and array.

```ruby
# range-block-vs-to_proc.rb
require 'benchmark/ips'

RANGE = (1..100)

def slow
  RANGE.map { |i| i.to_s }
end

def fast
  RANGE.map(&:to_s)
end

Benchmark.ips do |x|
  x.report('Block')          { slow }
  x.report('Symbol#to_proc') { fast }
  x.compare!
end
```

```ruby
# array-block-vs-to_proc.rb
require 'benchmark/ips'

ARRAY = [*1..100]

def slow
  ARRAY.map { |i| i.to_s }
end

def fast
  ARRAY.map(&:to_s)
end

Benchmark.ips do |x|
  x.report('Block')          { slow }
  x.report('Symbol#to_proc') { fast }
  x.compare!
end
```

with range:

```
$ ruby -v code/proc-and-block/range-block-vs-to_proc.rb
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
Calculating -------------------------------------
               Block     5.106k i/100ms
      Symbol#to_proc     5.846k i/100ms
-------------------------------------------------
               Block     51.180k (± 9.1%) i/s -    255.300k
      Symbol#to_proc     62.366k (± 6.0%) i/s -    315.684k

Comparison:
      Symbol#to_proc:    62366.2 i/s
               Block:    51179.9 i/s - 1.22x slower
```

with array:

```
ruby -v code/proc-and-block/array-block-vs-to_proc.rb
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
Calculating -------------------------------------
               Block     6.255k i/100ms
      Symbol#to_proc     7.327k i/100ms
-------------------------------------------------
               Block     60.362k (± 7.3%) i/s -    306.495k
      Symbol#to_proc     72.724k (± 5.3%) i/s -    366.350k

Comparison:
      Symbol#to_proc:    72723.9 i/s
               Block:    60361.9 i/s - 1.20x slower
```

Danke :smile:

**Comment by nning** [comment]
Oh, never mind... :smile:
In a hurry, I forgot the `*` in `ARRAY = [*1..100]`.

**Comment by JuanitoFatas** [comment]
@nning Thanks for checking in! :+1: :beers:

**Comment by monfresh** [comment]
It looks like this also depends on what the array contains. If you compare mapping the length of strings in an array, the block version is faster:

```ruby
require "benchmark/ips"

ARRAY = ["hello", "dear", "rubyist"].freeze

def long_map
  ARRAY.map { |string| string.length }
end

def short_map
  ARRAY.map(&:length)
end

Benchmark.ips do |x|
  x.report("long_map")  { long_map }
  x.report("short_map") { short_map }
  x.compare!
end
```

```
Calculating -------------------------------------
            long_map    90.276k i/100ms
           short_map    83.631k i/100ms
-------------------------------------------------
            long_map      2.335M (± 6.3%) i/s -     11.646M
           short_map      1.802M (± 8.2%) i/s -      8.949M

Comparison:
            long_map:  2334720.0 i/s
           short_map:  1801578.7 i/s - 1.30x slower
```
