### ISSUE TITLE
Hash#fetch with argument vs Hash#fetch + block

### ISSUE THREAD

**Issue by mnarayan01** [JuanitoFatas/fast-ruby#39]
This one seems a bit misleading. Simply switching the default to e.g. a symbol or constant-defined string makes both versions perform essentially identically (the argument version is actually slightly faster).

The difference in the current version is (AFAIK) exclusively due to the time taken to allocate the string (which is elided in the block version). This makes the displayed time comparison quite misleading (at least from my perspective), as the ratio can be increased/decreased at will be changing the runtime of the default expression.

**Comment by mnarayan01** [comment]
Also I guess it's worth noting that if the `fetch` misses, the argument version is always faster.

**Comment by ixti** [comment]
@mnarayan01 Difference in those two forms is that in case of:

``` ruby
obj.fetch("foo", "bar")
```

you are creating two `String` objects always, while in case of

``` ruby
obj.fetch("foo") { "bar" }
```

one `String` is created, and second one created only if Hash has no such key.

So, of course if your default value is a constant, block-less form is a pure win:

``` ruby
BAR = "bar".freeze

obj.fetch("foo", nil)
obj.fetch("foo", :bar)
obj.fetch("foo", BAR)

# etc...
```

**Comment by JuanitoFatas** [comment]
@ixti Thanks for your explanations! :musical_note:  

@mnarayan01 Thank you for bringining this! Does @ixti's reply clear your concerns? Do you have suggestions on improving [current example code](https://github.com/JuanitoFatas/fast-ruby/blob/master/code/hash/fetch-vs-fetch-with-block.rb)? Thanks! :bow:

**Comment by ixti** [comment]
@JuanitoFatas yeah, I guess link to this issue is the simplest way :D Thanks!

**Comment by mnarayan01** [comment]
Yea think it's perfect now. :+1:
