### ISSUE TITLE
enumerable sort  vs sort_by

### ISSUE THREAD

**Issue by fremn** [JuanitoFatas/fast-ruby#63]
noticed that in the test for **enumerable sort  vs sort_by**  `sort_by` uses `symbol.to_proc` while `sort` uses a block. wouldn't this effect the results since another tests shows symbol to proc is faster than block?

**Comment by JuanitoFatas** [comment]
In [sort example code](https://github.com/JuanitoFatas/fast-ruby/blob/b5ea35c45c83fe31045bed675d6dea8b64aec655/code/enumerable/sort-vs-sort_by.rb#L8-L10):

```ruby
ARRAY.sort { |a, b| a.name <=> b.name }
```

I don't know how to make `sort` example in `Symbol#to_proc` form. So have to use `sort` this way to archieve same result with `sort_by`.

**Comment by fremn** [comment]
yeah i don't think you can change `sort` but `sort_by` maybe
```
def fast
  ARRAY.sort_by { |a| a.name }
end
```

**Comment by JuanitoFatas** [comment]
I added e20d448 for fair comparison. Thanks for bring this up! :+1:

**Comment by fremn** [comment]
you're welcome
