### ISSUE TITLE
JRuby warmup

### ISSUE THREAD

**Issue by rjnienaber** [JuanitoFatas/fast-ruby#69]
This was sort of touched upon in #23 in the sense that JRuby may end up doing something different from MRI. The one major problem I see with these benchmarks is they don't include a warm up phase which the JVM sometimes uses for optimisation. There are potentially [other things](http://stackoverflow.com/a/513259) that we would want to enable specifically for JRuby.

**Comment by JuanitoFatas** [comment]
Hi! I have no experience with JRuby but would love to see some optimisations pre-configured for JRuby. Does JRuby optimisations affects MRI? If not we can add those optimizations and make it fair for JRuby. Feel free to open pull request for this, thanks so much!

**Comment by rjnienaber** [comment]
> Does JRuby optimisations affects MRI? If not we can add those optimizations and make it fair for JRuby. 

I don't think so. The optimisations talked about in that StackOverflow post are specific to the JVM. I'll see what I can do.
