### ISSUE TITLE
"begin...rescue vs respond_to? for Control Flow"

### ISSUE THREAD

**Issue by jrunning** [JuanitoFatas/fast-ruby#80]
https://gist.github.com/jrunning/0e18236c6363af15c520

**Comment by dideler** [comment]
Would be nice if a bit more effort went into creating the issue, otherwise the effort that went into benchmarking is wasted as no action will be taken, besides maybe closing the issue.

What are you proposing?

**Comment by jrunning** [comment]
@dideler: This issue is an accidental duplicate of #81. I thought I had closed this one; I'm doing so now.
