### ISSUE TITLE
Hash fetch with symbols vs strings.

### ISSUE THREAD

**Issue by ixti** [JuanitoFatas/fast-ruby#83]
Description is not really correct. Difference between `:symbol` key and `"string"` keys is that Symbols are immutable constants, while in case of using a String key you creating that string over and over again. Starting with Ruby 2.1, you can mark string as frozen and it will be created only once:

``` ruby
10.times.map { "foobar".object_id }.uniq.count # => 10
10.times.map { "foobar".freeze.object_id }.uniq.count # => 10
```

See:
- https://github.com/JuanitoFatas/fast-ruby#hash-vs-hashfetch-code
- https://github.com/JuanitoFatas/fast-ruby/blob/master/code/hash/bracket-vs-fetch.rb

**Comment by ixti** [comment]
Oh. I'm sorry. Didn't read [article mentioned in description](http://www.sitepoint.com/unraveling-string-key-performance-ruby-2-2/) to the bottom. It actually mentions `.freeze` and some more info.

**Comment by ixti** [comment]
Note for myself: read linked articles from the top to the bottom before giving any advices :D

**Comment by JuanitoFatas** [comment]
> Oh. I'm sorry. Didn't read article mentioned in description to the bottom. It actually mentions .freeze and some more info.

Not at all! Thanks for opening this issue.
